services:
  adapter:
    image: adapter
    container_name: adapter
    build:
      context: ./adapter
      dockerfile: Dockerfile
    networks:
      - adapter_network
      - db_network
    environment:
      - DEBUG_DATA_FLOW=True
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=sp@rt@n
      - INFLUXDB_ORG=mafia
      - BROKER_HOST=mosquitto
      - BROKER_PORT=1883
    depends_on:
      - influxdb
      - mosquitto
    restart: always
  
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    networks:
      - db_network
      - grafana_network
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=belea
      - DOCKER_INFLUXDB_INIT_PASSWORD=spartan2k25
      - DOCKER_INFLUXDB_INIT_ORG=mafia
      - DOCKER_INFLUXDB_INIT_BUCKET=tema3
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=sp@rt@n
    volumes:
      - influxdb_data:/var/lib/influxdb2
    restart: always
  
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883
    networks:
      - adapter_network
    restart: always
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - influxdb
    networks:
      - grafana_network
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=asistent
      - GF_SECURITY_ADMIN_PASSWORD=grafanaSCD2024
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning

networks:
  adapter_network:
  db_network:
  grafana_network:

volumes:
  influxdb_data:
  grafana_data: